spring.application.name=ChairShop
server.port=8081

#JWT
jwt.secret=/tBDoSL++FMmfCoGIk9lPnNH+Zw+tsG91DMc/Ae4IevDL7Gd+1TAU7UuAidJDm+tElXiLrxrqWOhJ3mi891Dgw==
jwt.lifetime=3600000
jwt.expiration= 103600000

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/chair_shop
spring.datasource.username=postgres
spring.datasource.password=Postgres
spring.datasource.driver-class-name=org.postgresql.Driver


#Jpa
spring.jpa.properties.hibernate.default_schema=v1_iam_service
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_iam_service

#Logging Level
logging.level.com.post_hub.iam_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG